- name: Install the latest version of Development Tools
  dnf:
    name:
      - "@Development Tools"
    state: latest
  when: ansible_os_family == 'RedHat'
  become: yes

- name: Install the latest version of Build Essential
  apt: 
      pkg: 
          - build-essential
      state: latest
  when: ansible_distribution == 'Ubuntu'
  become: yes

- name: Install singularity dependencies for RedHat
  dnf:
    name:
      - openssl-devel
      - libuuid-devel
      - libseccomp-devel
      - wget
      - squashfs-tools
    state: latest
  when: ansible_os_family == 'RedHat'
  become: yes

- name: Install software dependencies for ubuntu
  apt:
    pkg:
      - libssl-dev
      - uuid-dev
      - libgpgme11-dev
      - squashfs-tools
      - libseccomp-dev
      - pkg-config
    state: latest
  when: ansible_distribution == 'Ubuntu'
  become: true

- name: Unarchive go
  ansible.builtin.unarchive:
    src: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes
  become: yes

- name: Download singularity from github
  git:
    repo: https://github.com/sylabs/singularity.git
    version: "{{ singularity_version }}"
    dest: "{{ home }}/singularity/src/github.com/sylabs/singularity"

- name: Compile singularity binary mconfig
  shell: "export PATH=/usr/local/go/bin:$PATH; ./mconfig --prefix=/usr/local"
  args:
    chdir: "{{ home }}/singularity/src/github.com/sylabs/singularity"
  become: yes

- name: Make singularity
  make:
    chdir: "{{ home }}/singularity/src/github.com/sylabs/singularity/builddir"
  become: yes

- name: Install singularity
  make:
    target: install
    chdir: "{{ home }}/singularity/src/github.com/sylabs/singularity/builddir"
  become: yes

- name: Delete go installer
  file:
    state: absent
    path: "{{ home }}/go"
  become: yes

- name: Delete singularity installer
  file:
    state: absent
    path: "{{ home }}/singularity"
  become: yes
