- name: Install the latest version of Development Tools
  dnf:
    name:
      - "@Development Tools"
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Install singularity dependencies
  dnf:
    name:
      - openssl-devel
      - libuuid-devel
      - libseccomp-devel
      - wget
      - squashfs-tools
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Unarchive go
  ansible.builtin.unarchive:
    src: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes

- name: Add to PATH
  copy:
    content: "export PATH=$PATH:/usr/local/go/bin"
    dest: "/etc/profile.d/go_path.sh"

- name: Download singularity from github
  git:
    repo: https://github.com/sylabs/singularity.git
    version: "{{ singularity_version }}"
    dest: "{{ home }}/singularity/src/github.com/sylabs/singularity"

- name: Compile singularity binary
  shell: "export PATH=/usr/local/go/bin:$PATH; ./mconfig --prefix=/usr/local"
  args:
    chdir: "{{ home }}/singularity/src/github.com/sylabs/singularity"

- name: Make singularity
  make:
    chdir: "{{ home }}/singularity/src/github.com/sylabs/singularity/builddir"

- name: Install singularity
  make:
    target: install
    chdir: "{{ home }}/singularity/src/github.com/sylabs/singularity/builddir"

- name: Delete go installer
  file:
    state: absent
    path: "{{ home }}/go"

- name: Delete singularity installer
  file:
    state: absent
    path: "{{ home }}/singularity"

