- name: install singularity dependencies
  dnf:
    name:
      - openssl-devel
      - libuuid-devel
      - libseccomp-devel
      - wget
      - squashfs-tools
    state: latest

- name: download go for singularity
  get_url:
   url: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
   dest: "{{ home }}"
   mode: 0755

- name: install go for singularity
  shell: "tar -C /usr/local -xzf {{ home }}/go{{ go_version }}.linux-amd64.tar.gz"
